### ISSUE TITLE
'npm start' returns syntax error in server.js 

### ISSUE THREAD

**Issue by sguldemond** [Alliander/diva-js-reference-3p-backend#39]
Hi, yesterday I met @timenolthof and he told me about the DIVA project, so I'm trying to get it running on my machine :)

After running `npm start` (and `npm install` before that) I get the following error message:

```
/foobar/diva-js-reference-3p-backend/src/server.js:32
    ...jwtDisclosureRequestOptions,
    ^^^
SyntaxError: Unexpected token ...
```

I think my 'node' is missing a module to digest the `...` - spread syntax. I can't seem to find the correct module to handle it, could someone nod me in the right direction?

Thanks!

Stan

**Comment by timenolthof** [comment]
Hi Stan, the spread operator is only supported is only supported from node 8.2.1 and up and currently we use node version 8.6.0 for diva. Using that version might solve your problem.
Optionally, you could use something like `nvm` to manage node versions efficiently.

@koen92 we should add engine requirements to package.json for all diva projects (see for example http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html ). I've created a ticket on the board.

**Comment by sguldemond** [comment]
Thanks, that did the trick!
